import React, { useState } from "react";
import { Button } from "./ui/button";
import { Badge } from "./ui/badge";
import { Progress } from "./ui/progress";
import { Card, CardContent } from "./ui/card";
import { Avatar, AvatarFallback } from "./ui/avatar";
import { ScrollArea } from "./ui/scroll-area";
import { useAuth } from "../context/AuthContext";
import { Settings } from "lucide-react";
import CharacterDisplay from "../components/CharacterDisplay";
import CharacterGallery from "../components/CharacterGallery";
import OfflineIncomeDialog from "../components/OfflineIncomeDialog";
import AdminMenu from "../plugins/admin/AdminMenu";
import AIChat from "../plugins/aicore/AIChat";
import LevelUp from "../plugins/gameplay/LevelUp";
import Upgrades from "../plugins/gameplay/Upgrades";
import WheelGame from "../components/wheel/WheelGame";
import VIP from "../components/vip/VIP";
import { useGameState } from "../hooks/use-game-state";
import { useGame } from "../context/GameProvider";
import { useToast } from "../hooks/use-toast";
import { apiRequest, queryClient } from "../lib/queryClient";
import { useQuery } from "@tanstack/react-query";
import PlayerStatsPanel from "../components/game/PlayerStatsPanel";
import GameTabsPanel from "../components/game/GameTabsPanel";
import FloatingActionIcons from "../components/ui/FloatingActionIcons";
import GameProgressPanel from "../components/game/GameProgressPanel";
import TasksPanel from "../components/game/TasksPanel";
import AchievementsPanel from "../components/game/AchievementsPanel";
import DebuggerConsole from "../components/debug/DebuggerConsole";

// ... rest of file unchanged ...
